-- Create the hospitals table
CREATE TABLE hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    contact TEXT,
    beds INTEGER DEFAULT 0,
    distance TEXT
);

-- Insert initial data (same as in data.js)
INSERT INTO hospitals (name, location, lat, lng, contact, beds, distance) VALUES
('CHARUSAT Hospital', 'Changa', 22.5996, 72.8205, '+91-2697-265000', 12, '1.2 km'),
('Primary Health Center (PHC)', 'Changa', 22.6020, 72.8250, '+91-2697-222333', 4, '2.5 km'),
('V. R. Patel Public Hospital', 'Ramol', 22.5700, 72.8000, '+91-98765-43210', 25, '5.0 km'),
('Ved Multispeciality Hospital', 'Vaso', 22.6500, 72.7500, '+91-268-2580123', 30, '12.0 km'),
('Zydus Hospital', 'Anand', 22.5645, 72.9289, '+91-2692-228500', 45, '18.5 km'),
('Shree Krishna Hospital', 'Karamsad', 22.5311, 72.9099, '+91-2692-228411', 60, '16.8 km');

-- Enable Row Level Security (RLS)
ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for everyone
CREATE POLICY "Allow public read access" 
ON hospitals FOR SELECT 
TO anon 
USING (true);
